#:schema node_modules/wrangler/config-schema.json
name = "loggery"
main = "src/index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]
experimental_assets = { directory = "./public", binding = "ASSETS" }
